version: '3.9'
services:
  db:
    image: mongo
    restart: always
    expose:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: fjs-diplom
    volumes:
      - mongovolume:/data/db
      - ./backend/mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - HTTP_PORT=5000
      - JWT_SECRET=secret
      - JWT_EXPIRES=3d
      - MONGO_URI=mongodb://mainuser:mainuserpassword@db:27017/fjs-diplom
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    tty: true
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mongovolume: